### PR TITLE
Playback control improvements

### LINKED ISSUE #22: Playlist restarts when paused then played
Trying to investigate. Using v `1.2.2`
Will update if I make any progress on it.

#### To reproduce:
1. Load a playlist, play it
2. Advance to a song other than the first using `player.next()`
3. Pause, then play it again, and it will start from the beginning of the playlist

#### Expected:
Should retain the position in the playlist after paused/played.

### PR DESCRIPTION
**Pull request by ivangreene**
Resolves #22 
Also adds loop option for `player.next()` to start at the beginning of a playlist if at the last track.

I've also changed the build script to create minified+unminified builds using `tee`. Unsure how portable this is (is tee standard on Windows?). May be reverted if you don't want that.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -155,7 +155,11 @@ SoundCloud.prototype.play = function (options) {
   } else if (this._playlist) {
     var length = this._playlist.tracks.length;
     if (length) {
-      this._playlistIndex = options.playlistIndex || 0;
+      if (options.playlistIndex === undefined) {
+        this._playlistIndex = this._playlistIndex || 0;
+      } else {
+        this._playlistIndex = options.playlistIndex;
+      }
```
Comment (voronianski) [inline index.js]: @ivangreene why not?
```
this._playlistIndex = options.playlistIndex || this._playlistIndex || 0;
```

File: package.json [hunk 2]
```diff
@@ -8,8 +8,9 @@
   },
   "scripts": {
     "start": "watchify . -s SoundCloudAudio -o dist/soundcloud-audio.js -v -d",
-    "build": "browserify . -s SoundCloudAudio | uglifyjs -cm > dist/soundcloud-audio.min.js",
+    "build": "browserify . -s SoundCloudAudio | tee dist/soundcloud-audio.js | uglifyjs -cm > dist/soundcloud-audio.min.js",
```
Comment (voronianski) [inline package.json]: @ivangreene please remove `tee`

File: index.js (hunk 1 above)
Comment (ivangreene) [reply index.js]: I originally had pretty much exactly this, but `.play({playlistIndex: 0})` would not be accepted as 0 is a falsey value.

Comment (ivangreene) [reply index.js]: do you have another way that goes more with your code style so that passing `0` would still be acknowledged when `this._playlistIndex` is nonzero?
